# List and Arrays

In [2]:
import numpy as np

In [3]:
L = [1,2,3] # List

In [4]:
A = np.array([1,2,3]) ## array

In [6]:
for e in L:
    print(e)

1
2
3


In [7]:
for e in A:
    print(e)

1
2
3


In [8]:
### Add new Item
L.append(4)
L

[1, 2, 3, 4]

In [9]:
A.append(4)

###array is fixed

AttributeError: 'numpy.ndarray' object has no attribute 'append'

In [10]:
## concat 
L + [5]

[1, 2, 3, 4, 5]

In [12]:
## Added
### Broadcasting 
# A + [4] 
A + np.array([4])

array([5, 6, 7])

In [13]:
A + np.array([4,5,6])

array([5, 7, 9])

In [15]:
A + np.array([4,5])
## wrong shape, 1 is sonderfall

ValueError: operands could not be broadcast together with shapes (3,) (2,) 

In [16]:
2 * A

array([2, 4, 6])

In [20]:
2 * L == L + L
L + L

[1, 2, 3, 4, 1, 2, 3, 4]

In [21]:
L2 = []
for e in L:
    L2.append(e+3)

L2

[4, 5, 6, 7]

In [22]:
L2 = [e+3 for e in L]
L2

[4, 5, 6, 7]

In [23]:
## Square
L2 = [e**2 for e in L]
L2

[1, 4, 9, 16]

In [24]:
A**2 # np.log / sqrt / exp

array([1, 4, 9])

In [25]:
np.tanh(A)

array([0.76159416, 0.96402758, 0.99505475])